openapi: "3.0.0"
info:
  version: 1.0.0
  title: Afes73 website API
servers:
  - url: https://api.afes.info/
  - url: http://localhost:8000/ # for local test

paths:

components:
  schemas:
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
