name: publish as package

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Cache packages in node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys:
            ${{ runner.os }}-node_modules-
      - name: install packages
        run: yarn install
      - name: build
        run: yarn build
      - name: prepare npm config
        run: npm config set //registry.npmjs.org/:_authToken=$NPM_TOKEN
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: publish
        run: npm publish --access public
        if: ${{ contains(github.ref, 'alpha') == false }}
      - name: publish as alpha
        run: npm publish --access public --tag alpha
        if: ${{ contains(github.ref, 'alpha') == true }}
