name: Test Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Cache packages in node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys:
            ${{ runner.os }}-node_modules-
      - name: install packages
        run: yarn install
      - name: lint (prettier)
        run: yarn prettier:check
      - name: lint (eslint)
        run: yarn eslint:check
      - name: build
        run: yarn build
  version:
    runs-on: ubuntu-latest
    if: !contains(github.event.pull_request.labels.*.name, 'skip-version')
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: check version differences
        run: git diff ${{ github.payload.pull_request.head.ref }} -- package.json | grep '"version"'
